
# MkDocs configuration file for the PortPy documentation site.
# This file defines the site title, theme, navigation structure, plugins, and custom styling/scripts.
# It uses the Material for MkDocs theme and includes pages for user guides, tutorials, API reference, and more.

# ----  Site metadata shown in the browser and used for SEO --------

#site_name: PortPy
site_name: ""
site_description: Open-source Python library for radiation therapy planning and optimization.
site_author: PortPy Contributors
repo_url: https://github.com/PortPy-Project/PortPy  # Link to the GitHub repository (shown in top-right corner)
repo_name: PortPy on GitHub

# ---- Theme and appearance settings using Material for MkDocs --------

theme:
  name: material
  logo: images/PortPy_logo.png                      # Logo shown in the navigation bar
  favicon: images/PortPy_logo.png                   # Icon shown in browser tabs
  palette:                                          # Define light and dark color schemes                          
    - scheme: default
      primary: "#4051b5"
      accent: "#009688"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  # Set fonts for text and code                                                     
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
    - navigation.instant                              # Instantly loads new pages without full reload
    #- navigation.tabs                                 # Displays top-level navigation as horizontal tabs    
    - navigation.top                                  # Keeps the top navigation bar visible while scrolling (sticky header)
    #- toc.integrate                                   # Integrates table of contents into the side navigation
    - search.suggest                                  # Suggests search terms as you type
    - search.highlight                                # Highlights search terms in the results

    - content.code.annotate                       # works with the pymdownx.inlinehilite and pymdownx.snippets extensions.  
                                                  # It allows highlighting specific parts of code and provides explanations inline using custom syntax.(like ==highlight== or --comment-- formats)
    - content.code.copy                           # Adds a copy button to code blocks for easy copying 


# --------Navigation structure for the sidebar and top menu --------

nav:
  - Home: index.md
  - Quick Start: quick_start.md
  - Tutorials:
      - Introduction: tutorials/introduction.md
      - Data Loading: tutorials/data_loading.md
      - Plan Optimization: tutorials/plan_optimization.md
      - Plan Evaluation: tutorials/plan_evaluation.md
      - Global Optimization: tutorials/global_optimization.md
      - TPS Integration: tutorials/tps_integration.md
  #- Benchmark Datasets: benchmark_datasets.md
  - FAQ: FAQ.md
  - Contact Us: contact_us.md
  - Resources: resources.md
  - Extensions:
      - Overview: extensions/overview.md
      - CompressRTP: extensions/compressRTP.md
      - ECHO-VMAT: extensions/echo_vmat.md


  


# --------MkDocs plugins used to enhance functionality --------

plugins:
  - search                                              # Adds search functionality
  - mkdocstrings:                                       # Automatically builds API documentation from Python docstrings in the 'portpy' package
      handlers:
        python:
          paths: [portpy]                               # Specify the path to the Python package for API documentation  
  - awesome-pages                                       # Allows for easy creation of a multi-level navigation structure with .pages files
  - minify                                              # Minifies HTML, CSS, and JavaScript files for faster loading
  - mermaid2                                            # Enables rendering of Mermaid diagrams in Markdown files
  - mkdocs-jupyter                                      # Allows for embedding Jupyter notebooks in Markdown files
 # - mike                                                # Used for versioning the documentation
  - tags                                                # Adds support for tagging pages in the documentation

# ---- Markdown Extensions ----

markdown_extensions:                                    # Adds features to Markdown rendering
  - admonition                                          # Enables note, warning, and tip blocks
  - codehilite                                          # Syntax highlighting for code blocks  
  - footnotes                                           # Enables footnotes in Markdown
  - toc:                                                # Table of contents settings
      permalink: true
      toc_depth: 0
  - pymdownx.superfences                                # Enables nested code blocks
  - pymdownx.highlight                                  # Syntax highlighting for code blocks
  - pymdownx.details                                    # Expandable details blocks
  - pymdownx.tabbed                                     # Tabbed content blocks

# -------- Extra Site Settings --------

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PortPy-Project/PortPy
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/portpy-photon/

extra_javascript: # Include custom JavaScript files
  - js/extra.js

extra_css: # Include custom CSS files
  - styles/extra.css
